spring.application.name=hospitalManegment


spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=postgres
spring.datasource.password=sahil
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

jwt.secret=VGhpc0lzTXlWZXJ5U2VjcmV0S2V5Rm9ySG9zcGl0YWxNYW5hZ2VtZW50UHJvamVjdDIwMjZKd3RUb2tlbg==
jwt.expiration=86400000